name: Deploy Astro site to Pages

on:
  # Se ejecuta en pushes al branch especificado (ej. main, master)
  push:
    branches: [ master ] # Cambia 'main' si tu rama principal es otra (ej. master)

  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos necesarios para el GITHUB_TOKEN
permissions:
  contents: read
  pages: write      # Para desplegar en gh-pages
  id-token: write   # Para autenticar con OIDC

# Permitir solo un despliegue concurrente, cancelando ejecuciones antiguas/pendientes
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # O la versión de Node que use tu proyecto
          cache: 'npm' # O 'yarn', 'pnpm' según tu gestor de paquetes

      - name: Install dependencies
        run: npm ci # O 'yarn install --frozen-lockfile', 'pnpm install --frozen-lockfile'

      - name: Build your Astro site
        run: npm run build # O 'yarn build', 'pnpm build' (asegúrate que este script exista en tu package.json)

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Sube el contenido de la carpeta 'dist' (salida por defecto de Astro)
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
